### ISSUE TITLE
cvxopt 示例

### ISSUE THREAD

**Issue by OneStepAndTwoSteps** [luwill/machine-learning-code-writing#6]
121页中的（9-34）中的二次规划前面存在系数1/2，能说明一下为什么在代码中不需要体现这个系数吗？我尝试在变量P中添加一个1/2系数发现虽然最小值不变，但是求出来的x发生了变化，虽然最小值可以忽略系数，但是x结果却变了，这个1/2系数能正常舍去吗？

**Comment by luwill** [comment]
一般情况下不建议舍去，按照实际目标函数的表达式来写。
可参考cvxopt官方例子：http://cvxopt.org/examples/tutorial/qp.html

**Comment by luwill** [comment]
closed.

**Comment by OneStepAndTwoSteps** [comment]
好的，谢谢。能简单解释一下qp返回数据的含义吗，pcost/dcost/gap/pres/dres ，因为我并没有在官方文档中找到这个解释。
